---
es_host: elasticsearch.example.com
es_port: 9200

writeback_index: elastalert
doc_type: 'doc'
rules_folder: /config/rules
run_every: { minutes: 1 }
buffer_time: { minutes: 15 }
realert: { days: 1 }
alert_time_limit: { days: 2 }
